'use strict';

const fs = require('fs');
const path = require('path');

const root = __dirname;
const outputDirectory = path.join(root, 'dist');

function read(filename) {
  return fs.readFileSync(path.join(root, filename), 'utf8').trimEnd();
}

function browserBundle(filenames) {
  const sources = filenames.map(filename => `// ${filename}\n${read(filename)}`).join('\n\n');
  return `/* Generated by npm run build. Do not edit directly. */\n` +
    `(function markdownJsBrowserBundle() {\n'use strict';\n\n${sources}\n})();\n`;
}

fs.mkdirSync(outputDirectory, { recursive: true });
fs.writeFileSync(
  path.join(outputDirectory, 'htmlToMarkdown.js'),
  browserBundle(['htmlToMarkdown.js'])
);
fs.writeFileSync(
  path.join(outputDirectory, 'markdown.js'),
  browserBundle(['default_rules.js', 'markdown.js'])
);
fs.writeFileSync(
  path.join(outputDirectory, 'markdown-editor.js'),
  browserBundle(['default_rules.js', 'markdown.js', 'markdown_wysiwyg_editor.js'])
);

console.log('Built dist/htmlToMarkdown.js, dist/markdown.js, and dist/markdown-editor.js');
